{
  flake.modules.nixos.terminals =
    { inputs, pkgs, ... }:
    {

      environment.systemPackages =
        with pkgs;
        [
          ghostty
          kitty
        ];

      fonts.packages = with pkgs; [
        iosevka
        nerd-fonts.fira-code
        nerd-fonts.iosevka
        nerd-fonts.jetbrains-mono
        nerd-fonts.hack
        nerd-fonts.symbols-only
      ];

      fonts.fontconfig.enable = true;

      home-manager.sharedModules = [
        inputs.self.modules.homeManager.terminals
      ];
    };

  flake.modules.homeManager.terminals =
    { config, ... }:
    {
      # Use out-of-store symlinks so that ~/.config/ghostty and ~/.config/kitty
      # remain real writable directories, since themes are managed by hand
      # (not generated by matugen/DMS).
      home.file.".config/ghostty/config".source =
        config.lib.file.mkOutOfStoreSymlink /home/hugomvs/Projetos/nix-config/modules/dotfiles/ghostty/config;

      home.file.".config/kitty/kitty.conf".source =
        config.lib.file.mkOutOfStoreSymlink /home/hugomvs/Projetos/nix-config/modules/dotfiles/kitty/kitty.conf;
    };
}
