format = '''
$username$hostname$directory'''

right_format = '''
$status$cmd_duration
'''

scan_timeout = 10
add_newline = false

[status]
disabled = false
symbol = '✘ '

[cmd_duration]
disabled = false

